@hostname=localhost
@port=7177
GET https://{{hostname}}:{{port}}/Start/Index
###
GET https://{{hostname}}:{{port}}/Start/One
###
GET https://{{hostname}}:{{port}}/Start/Two
###
GET https://{{hostname}}:{{port}}/Start/Three
###
POST https://{{hostname}}:{{port}}/Start/Index
###
POST https://{{hostname}}:{{port}}/Start/One
###
POST https://{{hostname}}:{{port}}/Start/Two
###
POST https://{{hostname}}:{{port}}/Start/Three
###
GET https://www.belstu.by/
###
POST https://{{hostname}}:{{port}}/End/Three
